[deps]
BetaML = "024491cd-cc6b-443e-8034-08ea7eb7db2b"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CatBoost = "e2e10f9a-a85d-4fa9-b6b2-639a32100a12"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LightGBM = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
MLJTuning = "03970b2e-30c4-11ea-3135-d1576263f10f"
Maxnet = "81f79f80-22f2-4e41-ab86-00c11cf0f26f"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
SIRUS = "cdeec39e-fb35-4959-aadb-a1dd5dede958"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
